<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<p class="copyright">
    <img style="margin-bottom:-8px; width:25px" alt="shop123 log" src="<?php echo $block->getViewFileUrl('images/magento-icon.svg') ?>"> <a href="http://www.shop123.net" target="_blank" title="<?php /* @escapeNotVerified */ echo __('SHOP123') ?>"></a>
    <?php /* @escapeNotVerified */ echo __('Copyright &copy; %1 SHOP123. All rights reserved.', date('Y')) ?>
</p>
